# Generated by Django 4.1.4 on 2022-12-30 07:31

import account.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_number', models.CharField(choices=[('1', '+99455'), ('2', '+99450'), ('3', '+99451'), ('4', '+99470'), ('5', '+99477'), ('6', '+99499')], max_length=1, verbose_name='phone prefixes')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Ganjlik'), ('2', 'Narimanov'), ('3', '20 January')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='first name')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('phone', models.CharField(max_length=7)),
                ('gov_id', models.CharField(choices=[('1', 'AZE'), ('2', 'AA'), ('3', 'MYI'), ('4', 'DYI')], max_length=1, unique=True)),
                ('pin_code', models.CharField(max_length=7, unique=True)),
                ('client_code', models.CharField(default=account.helpers.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('monthly_expense', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.warehouse')),
                ('phone_prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.phoneprefix')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
