# Generated by Django 4.1.4 on 2023-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneprefix',
            name='prefix_number',
            field=models.CharField(choices=[('+99455', '+99455'), ('+99450', '+99450'), ('+99451', '+99451'), ('+99470', '+99470'), ('+99477', '+99477'), ('+99499', '+99499')], max_length=6, verbose_name='phone prefixes'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(choices=[('GN', 'Ganjlik'), ('NR', 'Narimanov'), ('20Jan', '20 January')], max_length=5),
        ),
    ]
