# Generated by Django 4.1.4 on 2023-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_customuser_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=25, verbose_name="last name"),
        ),
    ]
