# Generated by Django 4.1.4 on 2023-01-10 18:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gov_id_prefix',
            field=models.CharField(choices=[('1', 'AZE'), ('2', 'AA'), ('3', 'MYI'), ('4', 'DYI')], default='AZE', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gov_id',
            field=models.CharField(max_length=8, unique=True, validators=[account.models.validate_gov_id]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=7, validators=[account.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(max_length=7, unique=True, validators=[account.models.validate_pin_code]),
        ),
    ]
