# Generated by Django 4.1.4 on 2023-01-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_gov_id_prefix_alter_customuser_gov_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.warehouse'),
        ),
    ]
