# Generated by Django 4.1.4 on 2023-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_is_staff_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneprefix',
            name='prefix_number',
            field=models.CharField(choices=[('+99455', '+99455'), ('+99450', '+99450'), ('+99451', '+99451'), ('+99470', '+99470'), ('+99477', '+99477'), ('+99499', '+99499')], default='+99455', max_length=6),
        ),
    ]
