# Generated by Django 4.1.4 on 2023-01-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_phoneprefix_prefix_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(default='Ganjlik', on_delete=django.db.models.deletion.CASCADE, to='account.warehouse'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_prefix',
            field=models.OneToOneField(default='+99450', on_delete=django.db.models.deletion.CASCADE, to='account.phoneprefix'),
        ),
        migrations.AlterField(
            model_name='phoneprefix',
            name='prefix_number',
            field=models.CharField(choices=[('+99455', '+99455'), ('+99450', '+99450'), ('+99451', '+99451'), ('+99470', '+99470'), ('+99477', '+99477'), ('+99499', '+99499')], max_length=6),
        ),
    ]
