# Generated by Django 4.1.4 on 2023-01-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.phoneprefix'),
        ),
    ]
