# Generated by Django 4.1.4 on 2023-03-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_phone_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.warehouse'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.phoneprefix'),
        ),
    ]
