# Generated by Django 4.1.4 on 2023-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gov_id_prefix',
            field=models.CharField(choices=[('AZE', 'AZE'), ('AA', 'AA'), ('MYI', 'MYI'), ('DYI', 'DYI')], default='AZE', max_length=3),
        ),
    ]
