# Generated by Django 4.1.4 on 2023-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='country list')),
            ],
            options={
                'verbose_name': 'Counrty',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-add_time'], 'verbose_name_plural': 'News'},
        ),
    ]
