# Generated by Django 4.1.4 on 2023-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
    ]
