# Generated by Django 4.1.4 on 2023-01-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_slug'),
        ('core', '0003_country_enabled_alter_country_name'),
    ]

    operations = [
    ]
