# Generated by Django 4.1.4 on 2023-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20230128_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='currency name')),
                ('sign', models.CharField(max_length=1, verbose_name='currency sign')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
