# Generated by Django 4.1.4 on 2023-02-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20230128_1546'),
        ('core', '0005_contactus'),
    ]

    operations = [
    ]
