# Generated by Django 4.1.4 on 2023-02-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20230126_1307'),
        ('core', '0004_merge_20230201_1229'),
        ('core', '0005_currency'),
        ('core', '0006_merge_0004_merge_20230128_1546_0005_contactus'),
    ]

    operations = [
    ]
