# Generated by Django 4.1.4 on 2023-02-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20230211_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_or_percentage', models.CharField(choices=[('C', 'Constant'), ('P', 'Percentage')], max_length=1, verbose_name='constant or percentage')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount amount')),
                ('reason', models.CharField(max_length=150, unique=True, verbose_name='discount reason')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='FAQ_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the faq questions to be displayed.', verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocalWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='local warehouse address')),
                ('display_name', models.CharField(max_length=100, verbose_name='local warehouse name')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, verbose_name='local warehouse display order')),
            ],
            options={
                'verbose_name': 'Local Warehouse',
                'verbose_name_plural': 'Local Warehouses',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100, null=True, verbose_name='category name')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producttype', verbose_name='sub category name')),
            ],
            options={
                'verbose_name': 'Type of products',
                'verbose_name_plural': 'Types of products',
            },
        ),
    ]
