# Generated by Django 4.1.4 on 2023-02-11 14:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_merge_20230210_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_or_percentage', models.CharField(choices=[('C', 'Constant'), ('P', 'Percentage')], max_length=1, verbose_name='constant or percentage')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount amount')),
                ('reason', models.CharField(max_length=150, unique=True, verbose_name='discount reason')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        
    ]
