# Generated by Django 4.1.4 on 2023-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20230208_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='local warehouse address')),
                ('display_name', models.CharField(max_length=100, verbose_name='local warehouse name')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, verbose_name='local warehouse display order')),
            ],
            options={
                'verbose_name': 'Local Warehouse',
                'verbose_name_plural': 'Local Warehouses',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
