# Generated by Django 4.1.4 on 2023-02-16 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the faq questions to be displayed.', verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocalWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='local warehouse address')),
                ('display_name', models.CharField(max_length=100, verbose_name='local warehouse name')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, verbose_name='local warehouse display order')),
            ],
            options={
                'verbose_name': 'Local Warehouse',
                'verbose_name_plural': 'Local Warehouses',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Type of products', 'verbose_name_plural': 'Types of products'},
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='level',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='producttype',
            name='main_category',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producttype', verbose_name='sub category name'),
        ),
        migrations.CreateModel(
            name='ForeignWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('airwaybill_address', models.CharField(max_length=255, verbose_name='airwaybill address')),
                ('address_header', models.CharField(max_length=100, verbose_name='address header')),
                ('address_1', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=20)),
                ('gov_id', models.CharField(default='99674408434', max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='foreign country warehouse')),
                ('name_surname', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='name and surname')),
            ],
            options={
                'verbose_name': 'Foreign Warehouse',
                'verbose_name_plural': 'Foreign Warehouses',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(blank=True, verbose_name='answer')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the question to be displayed.', verbose_name='sort order')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0, verbose_name='status')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='created on')),
                ('updated_on', models.DateTimeField(verbose_name='updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('faq_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.faq_category', verbose_name='faq category')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Frequent asked question',
                'verbose_name_plural': 'Frequently asked questions',
                'ordering': ['sort_order', 'created_on'],
            },
        ),
    ]
