# Generated by Django 4.1.4 on 2023-02-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('next_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='declaration.packagestatus')),
            ],
            options={
                'verbose_name': 'Package Status',
                'verbose_name_plural': 'Package Status',
            },
        ),
    ]
