# Generated by Django 4.1.4 on 2023-02-23 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_faq_category_localwarehouse_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('next_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='declaration.packagestatus')),
            ],
            options={
                'verbose_name': 'Package Status',
                'verbose_name_plural': 'Package Status',
            },
        ),
        migrations.CreateModel(
            name='PackageDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_liquid', models.BooleanField(default=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='declarations/')),
                ('image', models.ImageField(upload_to='declarations/')),
                ('quantity', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('penalty_status', models.BooleanField(default=False)),
                ('penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_added_to_customs', models.BooleanField(default=False)),
                ('is_user_declared', models.BooleanField(default=False)),
                ('is_added_to_the_box', models.BooleanField(default=False)),
                ('is_depeshed', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localwarehouse')),
                ('discounts', models.ManyToManyField(blank=True, related_name='declarations', to='core.discount')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaration.packagestatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Declaration',
                'verbose_name_plural': 'Package Declarations',
            },
        ),
    ]
