# Generated by Django 4.1.4 on 2023-02-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='package status name')),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Package status',
                'verbose_name_plural': 'Package status',
            },
        ),
        migrations.AlterField(
            model_name='packagedeclaration',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='packagedeclaration',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaration.packagestatus'),
        ),
    ]
