# Generated by Django 4.1.4 on 2023-03-23 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_corrected'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaration.packagedeclaration')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaration.packagestatus')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status History',
                'ordering': ['-date_changed'],
            },
        ),
    ]
