# Generated by Django 4.1.4 on 2023-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0002_packagestatus_alter_packagedeclaration_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagestatus',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
